Holiday.create!(holidate: '2012/01/01', holiday: 'New Year\'s Day')
Holiday.create!(holidate: '2012/03/21', holiday: 'Human Rights Day')
Holiday.create!(holidate: '2012/04/06', holiday: 'Good Friday (Friday before Easter Sunday)')
Holiday.create!(holidate: '2012/04/09', holiday: 'Family Day (Monday after Easter Sunday)')
Holiday.create!(holidate: '2012/04/27', holiday: 'Freedom Day')
Holiday.create!(holidate: '2012/05/01', holiday: 'Workers\' Day')
Holiday.create!(holidate: '2012/06/16', holiday: 'Youth Day')
Holiday.create!(holidate: '2012/08/09', holiday: 'National Women\'s Day')
Holiday.create!(holidate: '2012/09/24', holiday: 'Heritage Day')
Holiday.create!(holidate: '2012/12/16', holiday: 'Day of Reconciliation')
Holiday.create!(holidate: '2012/12/17', holiday: 'Public holiday')
Holiday.create!(holidate: '2012/12/25', holiday: 'Christmas Day')
Holiday.create!(holidate: '2012/12/26', holiday: 'Day of Goodwill')
Holiday.create!(holidate: '2013/01/01', holiday: 'New Year\'s Day')
Holiday.create!(holidate: '2013/03/21', holiday: 'Human Rights Day')
Holiday.create!(holidate: '2013/03/29', holiday: 'Good Friday (Friday before Easter Sunday)')
Holiday.create!(holidate: '2013/04/01', holiday: 'Family Day (Monday after Easter Sunday)')
Holiday.create!(holidate: '2013/04/27', holiday: 'Freedom Day')
Holiday.create!(holidate: '2013/05/01', holiday: 'Workers\' Day')
Holiday.create!(holidate: '2013/06/16', holiday: 'Youth Day')
Holiday.create!(holidate: '2013/06/17', holiday: 'Public holiday')
Holiday.create!(holidate: '2013/08/09', holiday: 'National Women\'s Day')
Holiday.create!(holidate: '2013/09/24', holiday: 'Heritage Day')
Holiday.create!(holidate: '2013/12/16', holiday: 'Day of Reconciliation')
Holiday.create!(holidate: '2013/12/25', holiday: 'Christmas Day')
Holiday.create!(holidate: '2013/12/26', holiday: 'Day of Goodwill')
Holiday.create!(holidate: '2014/01/01', holiday: 'New Year\'s Day')
Holiday.create!(holidate: '2014/03/21', holiday: 'Human Rights Day')
Holiday.create!(holidate: '2014/03/18', holiday: 'Good Friday (Friday before Easter Sunday)')
Holiday.create!(holidate: '2014/03/21', holiday: 'Family Day (Monday after Easter Sunday)')
Holiday.create!(holidate: '2014/04/27', holiday: 'Freedom Day')
Holiday.create!(holidate: '2014/04/28', holiday: 'Public holiday')
Holiday.create!(holidate: '2014/05/01', holiday: 'Workers\' Day')
Holiday.create!(holidate: '2014/06/16', holiday: 'Youth Day')
Holiday.create!(holidate: '2014/08/09', holiday: 'National Women\'s Day')
Holiday.create!(holidate: '2014/09/24', holiday: 'Heritage Day')
Holiday.create!(holidate: '2014/12/16', holiday: 'Day of Reconciliation')
Holiday.create!(holidate: '2014/12/25', holiday: 'Christmas Day')
Holiday.create!(holidate: '2014/12/26', holiday: 'Day of Goodwill')
Holiday.create!(holidate: '2015/01/01', holiday: 'New Year\'s Day')
Holiday.create!(holidate: '2015/03/21', holiday: 'Human Rights Day')
Holiday.create!(holidate: '2015/03/18', holiday: 'Good Friday (Friday before Easter Sunday)')
Holiday.create!(holidate: '2015/03/21', holiday: 'Family Day (Monday after Easter Sunday)')
Holiday.create!(holidate: '2015/04/27', holiday: 'Freedom Day')
Holiday.create!(holidate: '2015/04/28', holiday: 'Public holiday')
Holiday.create!(holidate: '2015/05/01', holiday: 'Workers\' Day')
Holiday.create!(holidate: '2015/06/16', holiday: 'Youth Day')
Holiday.create!(holidate: '2015/08/09', holiday: 'National Women\'s Day')
Holiday.create!(holidate: '2015/09/24', holiday: 'Heritage Day')
Holiday.create!(holidate: '2015/12/16', holiday: 'Day of Reconciliation')
Holiday.create!(holidate: '2015/12/25', holiday: 'Christmas Day')
Holiday.create!(holidate: '2015/12/26', holiday: 'Day of Goodwill')
Holiday.create!(holidate: '2016/01/01', holiday: 'New Year\'s Day')
Holiday.create!(holidate: '2016/03/21', holiday: 'Human Rights Day')
Holiday.create!(holidate: '2016/03/18', holiday: 'Good Friday (Friday before Easter Sunday)')
Holiday.create!(holidate: '2016/03/21', holiday: 'Family Day (Monday after Easter Sunday)')
Holiday.create!(holidate: '2016/04/27', holiday: 'Freedom Day')
Holiday.create!(holidate: '2016/04/28', holiday: 'Public holiday')
Holiday.create!(holidate: '2016/05/01', holiday: 'Workers\' Day')
Holiday.create!(holidate: '2016/06/16', holiday: 'Youth Day')
Holiday.create!(holidate: '2016/08/09', holiday: 'National Women\'s Day')
Holiday.create!(holidate: '2016/09/24', holiday: 'Heritage Day')
Holiday.create!(holidate: '2016/12/16', holiday: 'Day of Reconciliation')
Holiday.create!(holidate: '2016/12/25', holiday: 'Christmas Day')
Holiday.create!(holidate: '2016/12/26', holiday: 'Day of Goodwill')


Employee.create!(sort: 1,finger: 2, surname: 'ADONIS', name: 'RALDA')
Employee.create!(sort: 2,finger: 9, surname: 'BOER', name: 'SHARON')
Employee.create!(sort: 3,finger: 15, surname: 'DAVIDS', name: 'CHANDRE')
Employee.create!(sort: 4,finger: 19, surname: 'DREYER', name: 'RAY-DEAN')
Employee.create!(sort: 5,finger: 26, surname: 'GWANE', name: 'NOMAROMA')
Employee.create!(sort: 6,finger: 33, surname: 'JOSEF', name: 'ROZANNE')
Employee.create!(sort: 7,finger: 36, surname: 'LEBESE', name: 'NOMBUKHELO')
Employee.create!(sort: 8,finger: 38, surname: 'QHOLE', name: 'LUMKA')
Employee.create!(sort: 9,finger: 40, surname: 'MALANGA', name: 'BABALWA')
Employee.create!(sort: 10,finger: 42, surname: 'MANELI', name: 'AMANDA')
Employee.create!(sort: 11,finger: 45, surname: 'MATAKATA', name: 'MIRANDA')
Employee.create!(sort: 12,finger: 46, surname: 'MBUTUMA', name: 'NTOMBOMZI')
Employee.create!(sort: 13,finger: 49, surname: 'MENE', name: 'PATIENCE')
Employee.create!(sort: 14,finger: 50, surname: 'MENDU', name: 'ALICIA')
Employee.create!(sort: 15,finger: 53, surname: 'MINNAAR', name: 'SAMANTHEA')
Employee.create!(sort: 16,finger: 62, surname: 'PIETERSEN', name: 'URSULA')
Employee.create!(sort: 17,finger: 63, surname: 'POTSO', name: 'ANDISWA')
Employee.create!(sort: 18,finger: 64, surname: 'POTSO', name: 'NONKULULEKO')
Employee.create!(sort: 19,finger: 65, surname: 'RONELLI', name: 'JANINE')
Employee.create!(sort: 20,finger: 74, surname: 'WITBOOI', name: 'ELMARIE')
Employee.create!(sort: 21,finger: 76, surname: 'ZONDI', name: 'NONKULUNGA PRIMROSE')
Employee.create!(sort: 22,finger: 77, surname: 'HECHTOR', name: 'CATHLEEN')
Employee.create!(sort: 23,finger: 80, surname: 'PIETERSEN', name: 'ESMERALDA')
Employee.create!(sort: 24,finger: 85, surname: 'WILLIAMS', name: 'LOURENE')
Employee.create!(sort: 25,finger: 92, surname: 'FESTERS', name: 'JANINE')
Employee.create!(sort: 26,finger: 97, surname: 'MFANTA (SICWEBU)', name: 'ZINGISA')
Employee.create!(sort: 27,finger: 101, surname: 'PONO', name: 'KHANGELWA')
Employee.create!(sort: 28,finger: 103, surname: 'GWE', name: 'JENNIFER NTOMBENKOSI')
Employee.create!(sort: 29,finger: 107, surname: 'BLES', name: 'NOSIPHO')
Employee.create!(sort: 30,finger: 108, surname: 'MAVUME', name: 'CYNTHIA NTOMBOVUYO')
Employee.create!(sort: 31,finger: 109, surname: 'MJEZU', name: 'DAPHNEY NTOMBIKAYISE')
Employee.create!(sort: 32,finger: 112, surname: 'NOMAXAYI', name: 'NOXOLO')
Employee.create!(sort: 33,finger: 119, surname: 'ARNOLDUS', name: 'BEVERLEY ALPHREIJ')
Employee.create!(sort: 34,finger: 121, surname: 'COLLINS', name: 'SHANETTE')
Employee.create!(sort: 35,finger: 124, surname: 'KORDOM', name: 'ROCHELLE')
Employee.create!(sort: 36,finger: 126, surname: 'MANELI', name: 'ZANDILE')
Employee.create!(sort: 37,finger: 128, surname: 'NTWANAMBI', name: 'THELMA')
Employee.create!(sort: 38,finger: 131, surname: 'DAVIDS', name: 'THALIA')
Employee.create!(sort: 39,finger: 144, surname: 'NQWENANI', name: 'THULISWA')
Employee.create!(sort: 40,finger: 145, surname: 'MADUBEDUBE', name: 'THOZAMA')
Employee.create!(sort: 41,finger: 157, surname: 'BALENI', name: 'NOLUTHANDO')
Employee.create!(sort: 42,finger: 158, surname: 'SIWELA', name: 'LINDIWE')
Employee.create!(sort: 43,finger: 159, surname: 'TSHOLOBA', name: 'WENDY')
Employee.create!(sort: 44,finger: 160, surname: 'MASETI', name: 'BABALWA')
Employee.create!(sort: 45,finger: 801, surname: 'WATTS', name: 'NICOLE')
Employee.create!(sort: 46,finger: 802, surname: 'MANKOPAN', name: 'LENDOLIEN')
Employee.create!(sort: 47,finger: 803, surname: 'DANIELS', name: 'DEIDRE')
Employee.create!(sort: 48,finger: 804, surname: 'PHILANDER', name: 'JACQUALINE')
Employee.create!(sort: 49,finger: 902, surname: 'BREYNARD', name: 'NORA')
Employee.create!(sort: 50,finger: 907, surname: 'ZONDI', name: 'UNATHI')
Employee.create!(sort: 51,finger: 944, surname: 'LINDIWE', name: 'BONGA')
Employee.create!(sort: 52,finger: 905, surname: 'MARSH', name: 'TESHQUENITA')
Employee.create!(sort: 53,finger: 920, surname: 'MGIDLANA', name: 'NOMALIBONGWE')
Employee.create!(sort: 54,finger: 922, surname: 'MBOSO', name: 'CYNTHIA')
Employee.create!(sort: 55,finger: 923, surname: 'MJEZU', name: 'QLWETHU')
Employee.create!(sort: 56,finger: 929, surname: 'MALAHLANA', name: 'ZIZIPHO')
Employee.create!(sort: 57,finger: 934, surname: 'DYORTA', name: 'NOMAWETHU')
Employee.create!(sort: 58,finger: 938, surname: 'BADULE', name: 'PILISWA')
Employee.create!(sort: 59,finger: 941, surname: 'MBANA', name: 'PHATHISWA')
Employee.create!(sort: 60,finger: 942, surname: 'KHOHLISO', name: 'NOMISILE')
Employee.create!(sort: 61,finger: 950, surname: 'MALGAS', name: 'NOKUPHUMA')
Employee.create!(sort: 62,finger: 951, surname: 'NOZUKO', name: 'MANZI')
Employee.create!(sort: 63,finger: 955, surname: 'NOMBULELO', name: 'MPELA')
Employee.create!(sort: 64,finger: 967, surname: 'LINDISWA', name: 'MZIZI')
Employee.create!(sort: 65,finger: 972, surname: 'MOSE', name: 'SIGNORIA')
Employee.create!(sort: 66,finger: 973, surname: 'NYAMBA', name: 'NONCEBA')
Employee.create!(sort: 67,finger: 983, surname: 'MANGXONGXOSA', name: 'UNATHI')
Employee.create!(sort: 68,finger: 989, surname: 'NGYANGA', name: 'TOMBI')
Employee.create!(sort: 69,finger: 990, surname: 'WITBOOI', name: 'JUSTINE')
Employee.create!(sort: 70,finger: 991, surname: 'JUBA', name: 'SILIDOKUHLE')
Employee.create!(sort: 71,finger: 996, surname: 'PONI', name: 'SINETHEMBA')
Employee.create!(sort: 72,finger: 1001, surname: 'NGUBO', name: 'ZANDILE')
Employee.create!(sort: 74,finger: 1004, surname: 'WELELE', name: 'NONTHUZELO')
Employee.create!(sort: 75,finger: 1006, surname: 'THANDIWE', name: 'NWABISA')
Employee.create!(sort: 76,finger: 1007, surname: 'MAVUME', name: 'THANDIWE')
Employee.create!(sort: 77,finger: 1008, surname: 'MFEKETHO', name: 'CYNTHIA')
Employee.create!(sort: 78,finger: 1009, surname: 'MFONO', name: 'ZOLISWA')
Employee.create!(sort: 79,finger: 1010, surname: 'PARKIES', name: 'MPHO')
Employee.create!(sort: 80,finger: 1011, surname: 'MANZINI', name: 'NOMAXABISO')
Employee.create!(sort: 81,finger: 1012, surname: 'MZINYATI', name: 'ABONGILE')
Employee.create!(sort: 82,finger: 1013, surname: 'THUSWA', name: 'SINDISWA')
Employee.create!(sort: 83,finger: 1015, surname: 'SAMBOKWE', name: 'BUSISIWE')
Employee.create!(sort: 84,finger: 1017, surname: 'NGQAKAVA', name: 'YONELA')
Employee.create!(sort: 85,finger: 1018, surname: 'KHONCO', name: 'THOBISA')
Employee.create!(sort: 86,finger: 1019, surname: 'HANI', name: 'NOKUPHELA')
Employee.create!(sort: 87,finger: 1020, surname: 'DYONTA ', name: 'NOKUPHIWE')
Employee.create!(sort: 88,finger: 1022, surname: 'MNGQIBISA ', name: 'CONSTANCE')
Employee.create!(sort: 89,finger: 1023, surname: 'VAN BOOM', name: 'MELONI')
Employee.create!(sort: 90,finger: 1026, surname: 'MULLER', name: 'RENE')
Employee.create!(sort: 91,finger: 1027, surname: 'MOAHLOLI', name: 'PULANE')
Employee.create!(sort: 92,finger: 1028, surname: 'SAMBOKWE', name: 'SINDISIWE')
Employee.create!(sort: 93,finger: 9991, surname: 'SINAZO', name: 'ALAM')
Employee.create!(sort: 94,finger: 9992, surname: 'BABALWE', name: 'MALOTANE')
Employee.create!(sort: 95,finger: 9993, surname: 'BONGISWE', name: 'GWE')
Employee.create!(sort: 96,finger: 9994, surname: 'BABALWE', name: 'MAMKELI')
Employee.create!(sort: 97,finger: 1029, surname: 'DYSON ', name: 'LENIE')
Employee.create!(sort: 98,finger: 1030, surname: 'SHELDON', name: 'ALETTA')
Employee.create!(sort: 99,finger: 1031, surname: 'THOMAS', name: 'ELMARIE')
Employee.create!(sort: 100,finger: 1032, surname: 'LOUW', name: 'ANNALINE')
Employee.create!(sort: 101,finger: 1033, surname: 'GEDULD', name: 'WILMA')
Employee.create!(sort: 102,finger: 1034, surname: 'JULIES', name: 'SUSAN')
Employee.create!(sort: 103,finger: 1035, surname: 'MORRIS', name: 'OLIVIA')
Employee.create!(sort: 104,finger: 1036, surname: 'ADAMS', name: 'BEATRICE')
Employee.create!(sort: 105,finger: 1037, surname: 'WILLIAMS', name: 'THURLIANE')
Employee.create!(sort: 106,finger: 1038, surname: 'BASSON', name: 'CHAN')
Employee.create!(sort: 107,finger: 1039, surname: 'VISSER', name: 'ABTHEA')
Employee.create!(sort: 108,finger: 1040, surname: 'VAN WYK', name: 'MARIA')
Employee.create!(sort: 109,finger: 1041, surname: 'LINNERT', name: 'DEIDRE')
Employee.create!(sort: 110,finger: 1042, surname: 'KOOPMAN', name: 'MELANIE')
Employee.create!(sort: 111,finger: 1043, surname: 'FORTUIN', name: 'MARGARET')
Employee.create!(sort: 112,finger: 1045, surname: 'SECONDS', name: 'JO-ANNE')
Employee.create!(sort: 113,finger: 1046, surname: 'SIAS ', name: 'RONITA')
Employee.create!(sort: 114,finger: 1047, surname: 'VLOK', name: 'CHRISTINA')
Employee.create!(sort: 115,finger: 1048, surname: 'MARTIN', name: 'SYLVIA')
Employee.create!(sort: 116,finger: 1049, surname: 'FORTUIN', name: 'MARIETTE')
Employee.create!(sort: 117,finger: 1050, surname: 'QHOLE', name: 'NWABISA')
Employee.create!(sort: 118,finger: 1051, surname: 'SIGWADI', name: 'AMANDA')
Employee.create!(sort: 119,finger: 1052, surname: 'ABRAHAMS', name: 'ROCHE')
